version: '3'
services:
  node:
    image: node:17
    container_name: flea_market_node
    ports:
      - 8080:3000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    tty: true

  postgres:
    image: postgres:12.2-alpine
    container_name: flea_market_postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: postgres
    hostname: postgres
    restart: always
    user: root
